version: 0.0
os: linux
files:
  - source: target/myapp.war
    destination: /opt/tomcat/webapps  # Replace with the actual Tomcat webapps directory

hooks:
  BeforeInstall:
    - location: scripts/stop_tomcat.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: scripts/start_tomcat.sh
      timeout: 300
      runas: root