dev:
  instance_type: "t2.micro"
  min_capacity: 1
  max_capacity: 2
  desired_capacity: 1
test:
  instance_type: "t2.medium"
  min_capacity: 2
  max_capacity: 4
  desired_capacity: 2
prod:
  instance_type: "t2.large"
  min_capacity: 3
  max_capacity: 6
  desired_capacity: 4